### ISSUE TITLE
Photon realtime issues

### ISSUE THREAD

**Issue by abrown1982** [oculus-samples/Unity-SharedSpaces#10]
Importing into Unity at the moment in the latest LTS version throws a couple of errors I've not been able to resolve.

`Library\PackageCache\com.community.netcode.transport.photon-realtime@1d5be27015\Runtime\PhotonRealtimeTransport.cs(260,30): error CS0115: 'PhotonRealtimeTransport.Initialize()': no suitable method found to override`

and

`Library\PackageCache\com.community.netcode.transport.photon-realtime@1d5be27015\Runtime\PhotonRealtimeTransport.Connection.cs(9,26): error CS0534: 'PhotonRealtimeTransport' does not implement inherited abstract member 'NetworkTransport.Initialize(NetworkManager)'`

Is there an obvious fix to this?  Thanks.

**Comment by pr0-zac** [comment]
It appears you have a newer version of Netcode for Gameobjects that is incompatible with the older version of Photon Realtime. You can check by comparing your manifest.json to [/Packages/manifest.json](https://github.com/oculus-samples/Unity-SharedSpaces/blob/main/Packages/manifest.json).

We haven't yet tested the project with the latest packages, but we found a [commit in Photon Realtime](https://github.com/Unity-Technologies/multiplayer-community-contributions/pull/153) that addresses this exact problem. 

You can either downgrade you Netcode for Gameobjects to pre5 or upgrade your Photon Realtime.

**Comment by pr0-zac** [comment]
We're going to consider this issue resolved. If you are still having trouble, please let us know.

**Comment by adrianktng** [comment]
Updated to the newer version 2.0.1 of "Photon Realtime Transport for Netcode for GameObjects" which removed the issues above but throw in two new errors in Unity 2021.3.10f1.

`Assets\SharedSpaces\Scripts\SharedSpacesSession.cs(28,25): error CS0176: Member 'NetworkManager.ServerClientId' cannot be accessed with an instance reference; qualify it with a type name instead`

`Assets\SharedSpaces\Scripts\SharedSpacesSession.cs(70,23): error CS0176: Member 'NetworkManager.ServerClientId' cannot be accessed with an instance reference; qualify it with a type name instead`
