### ISSUE TITLE
InvalidOperationException using latest Netcode for GameObjects

### ISSUE THREAD

**Issue by cchristensen-supernatural** [oculus-samples/Unity-SharedSpaces#11]
I'm using current Unity 2021 LTS version. The current Netcode for Game Objects package (1.0.2). I've applied the patch to Photon realtime mentioned in Issue #10.
Everything seems to work fine until you get 2 or more players in a room, and then the log is spammed with:
"InvalidOperationException: Client is not allowed to write to this"

And some of the players see the other players unable to move.

It seems that the updated Netcode for Game Objects removed the ability for clients to write to NetworkVariables as mentioned here: https://forum.unity.com/threads/networkvariable-write-permission.1176548/
So that seems like a likely culprit here. It would be nice to get this sample app working again.
Any pointers on how to fix it?

**Comment by cchristensen-supernatural** [comment]
I found a fix for it. The code in ClientNetworkTransform.cs just needs to be updated.
I replaced it with this:
https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/blob/main/Packages/com.unity.multiplayer.samples.coop/Utilities/Net/ClientAuthority/ClientNetworkTransform.cs

and the InvalidOperationException errors went away, and the characters are no longer getting stuck.

**Comment by pr0-zac** [comment]
Thanks for identifying this issue! Updating to the current version of Netcode for GameObjects is on our todo list. We will reply to this issue once it is complete.

**Comment by cchristensen-supernatural** [comment]
Thanks! Really glad to hear it.

**Comment by AlexThiv** [comment]
We updated the project to use Unity 2021.3.16f1 and fixed the related issues you mentioned due to the Netcode for GameObjects version change.
https://github.com/oculus-samples/Unity-SharedSpaces/commit/2dc4d4ef4bd6d6185c4fab1c4a459b5b09bc23b2
