### ISSUE TITLE
How to change text

### ISSUE THREAD

**Issue by ssdrive-flaktra** [oculus-samples/Unity-SharedSpaces#12]
Hey! I was wondering how to change the text in the lobby. I saw the "lobby_text_bc.png" image but had no idea what to edit. Any help would be appreciated!

**Comment by pr0-zac** [comment]
For performance reasons the text is baked into the scene. If you select the text in the editor, you can see that several pieces like the Lobby, Roster Panel, etc. are baked into a single mesh called lobby_text_sm. If you want to change any part of this, you'll need to replace this asset. We suggest using TextMesh Pro which is included in the project under the Assets directory.
