### ISSUE TITLE
Runtime error when building the project on Apple Silicon 

### ISSUE THREAD

**Issue by Elainen6** [oculus-samples/Unity-SharedSpaces#14]
Hi,

I'm new to Unity 3D, when I was trying to run theb project on my Macbook(Apple silicon) it gave me runtime error like this:

DllNotFoundException: OVRGamepad assembly:<unknown assembly> type:<unknown type> member:(null)
OVRInput+OVRControllerGamepadMac..ctor () (at Packages/Oculus/VR/Scripts/OVRInput.cs:2841)
OVRInput..cctor () (at Packages/Oculus/VR/Scripts/OVRInput.cs:284)
Rethrow as TypeInitializationException: The type initializer for 'OVRInput' threw an exception.
OVRControllerHelper.Update () (at Packages/Oculus/VR/Scripts/Util/OVRControllerHelper.cs:109)

I tried many ways and none of it seemed to work. I don't know if it's because of the fact that it's a M1 or package incompability.

**Comment by pr0-zac** [comment]
OVRControllerGamepadMac is no longer supported. We'll update the repo to fix this soon. For now, commenting out line 295 of OVRInput.cs should work. 
https://github.com/oculus-samples/Unity-SharedSpaces/blob/main/Packages/Oculus/VR/Scripts/OVRInput.cs#L295

**Comment by AlexThiv** [comment]
We updated to the Oculus Integration SDK v49 which fixes the error as it removes the deprecated OVRGamepad.
https://github.com/oculus-samples/Unity-SharedSpaces/commit/2dc4d4ef4bd6d6185c4fab1c4a459b5b09bc23b2
