### ISSUE TITLE
New rooms

### ISSUE THREAD

**Issue by ssdrive-flaktra** [oculus-samples/Unity-SharedSpaces#15]
How do I create new rooms in the sample? I've tried everything I know to no avail.

**Comment by els-oculus** [comment]
There are many steps to follow.

First you need to create your new destinations on the dashboard.
https://github.com/oculus-samples/Unity-SharedSpaces#2-destinations
Let us know how far you've got on that front.

As a side note, we do have a slightly different documentation for the Unreal version of SharedSpaces that is still relevant to you regarding the steps to create new rooms.   You can always have a look there if you wish to get  unstuck faster.
https://github.com/oculus-samples/Unreal-SharedSpaces/blob/main/Documentation/SharedSpaces.md#1b-social-networking-setting-your-group-presence

**Comment by ssdrive-flaktra** [comment]
> There are many steps to follow.
> 
> First you need to create your new destinations on the dashboard. https://github.com/oculus-samples/Unity-SharedSpaces#2-destinations Let us know how far you've got on that front.
> 
> As a side note, we do have a slightly different documentation for the Unreal version of SharedSpaces that is still relevant to you regarding the steps to create new rooms. You can always have a look there if you wish to get unstuck faster. https://github.com/oculus-samples/Unreal-SharedSpaces/blob/main/Documentation/SharedSpaces.md#1b-social-networking-setting-your-group-presence

Well, I did create a new destination on the dev dashboard and read the unreal engine one, but it's alien to me.

**Comment by pr0-zac** [comment]
Some additional details on setting up a new room:
* Duplicate one of the room scenes and rename it. For example, copy Scenes/RedRoom and call it Scenes/NewRoom.
* Duplicate one of the doors in the lobby. Copy PortalRedRoom, rename to PortalNewRoom. 
* The SharedSpacesPortal script has a room parameter that points to the Text object under PortalNewRoom>Canvas>Text. In there change "To Red Room" to "To New Room"
* Add a new enum value (NewRoom) to Scenes in SharedSpacesSceneLoader
* Add two new entries for NewRoom in the dictionary in SharedSpacesSceneLoader Start()
  * {"To New Room", Scenes.NewRoom}
  * {"NewRoom", Scenes.NewRoom}

Let us know if that works for you.

**Comment by pr0-zac** [comment]
Hope those instructions worked for you. Closing out this issue. Can reopen if more assistance is needed.

**Comment by ssdrive-flaktra** [comment]
works
