### ISSUE TITLE
Using Specified Version And Immediately When You Open This 2 Errors In Unity

### ISSUE THREAD

**Issue by Tonic3** [oculus-samples/Unity-SharedSpaces#17]
Library\PackageCache\com.community.netcode.transport.photon-realtime@1d5be27015\Runtime\PhotonRealtimeTransport.cs(260,30): error CS0115: 'PhotonRealtimeTransport.Initialize(NetworkManager)': no suitable method found to override

Library\PackageCache\com.community.netcode.transport.photon-realtime@1d5be27015\Runtime\PhotonRealtimeTransport.Connection.cs(9,26): error CS0534: 'PhotonRealtimeTransport' does not implement inherited abstract member 'NetworkTransport.Initialize()'

**Comment by pr0-zac** [comment]
This is the same as closed issue #10 . 

> It appears you have a newer version of Netcode for Gameobjects that is incompatible with the older version of Photon Realtime. You can check by comparing your manifest.json to [/Packages/manifest.json](https://github.com/oculus-samples/Unity-SharedSpaces/blob/main/Packages/manifest.json).
> 
> We haven't yet tested the project with the latest packages, but we found a https://github.com/Unity-Technologies/multiplayer-community-contributions/pull/153 that addresses this exact problem.
> 
> You can either downgrade you Netcode for Gameobjects to pre5 or upgrade your Photon Realtime.

**Comment by AlexThiv** [comment]
We have updated the project to Unity 2021.3.16f1, which integrates Netcode for GameObjects 1.1.0.
The update of Netcode was the source of the errors you were seeing and this has now been fixed with this updated.
https://github.com/oculus-samples/Unity-SharedSpaces/commit/2dc4d4ef4bd6d6185c4fab1c4a459b5b09bc23b2
