### ISSUE TITLE
New VRC

### ISSUE THREAD

**Issue by ssdrive-flaktra** [oculus-samples/Unity-SharedSpaces#18]
there is a new VRC guideline for user reporting, will this be added?

**Comment by AlexThiv** [comment]
Hi @AToska21,

If you look at the section "Updates to Developer Tools" in the [blog post](https://developer.oculus.com/blog/user-reporting-requirements-developer-tools-updates/) you can see the 2 ways to handle report.

For Shared Spaces we will keep the **User Reporting Service** as we don't plan on handling the reports ourselves. But you can look at the sample code for integrating the plugin [here](https://developer.oculus.com/resources/reporting-services?intern_source=devblog&intern_content=user-reporting-requirements-developer-tools-updates).
