### ISSUE TITLE
Adding additional Oculus Interaction SDK elements

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unity-SharedSpaces#19]
I am trying to add some additonal folders from the Oculus Integration so that I can add some elements from the Interaction SDK. Mainly I want to swap the player locomtion from TP to the standard OVR Camera Rig used in the example scenes in the Interaction SDK as I will be implmenting hand tracking and some other parts.

It looks like the Shared Spaces uses a custom version of the Oculus INtegartion which wont let me add any additonal directories from package manager. When attemtping to copy them in from another project it creates a long list of errors and duplication. 

How can I go about adding the Interaction SDK and most importantly changing the player perspective from the current one to the FP view and locomotion used in the Interaction SDK?

**Comment by jasonmeisel** [comment]
Hi @owlandfox! You should be able to simply delete the `Packages/Oculus` folder and then import the latest [Oculus Integration](https://developer.oculus.com/downloads/package/unity-integration/).

For more info on how to create a multiplayer game in First Person, I recommend checking out [Ultimate Glove Ball](https://github.com/oculus-samples/Unity-UltimateGloveBall).

**Comment by owlandfox** [comment]
Thanks - The gloveball demo does indeed look like the perfect template to integrate everything we need apart from a broken user flow moving between in game UI and Oculus platform UI. I left an issue over on that repo to check out with steps to reproduce thanks
