### ISSUE TITLE
Unity Exception: Can not sign the application.

### ISSUE THREAD

**Issue by SommerChase** [oculus-samples/Unity-SharedSpaces#20]
I was getting the error `Unity Exception: Can not sign the application` when trying to build the project. I did not make any edits to the project settings or anything.

I "fixed" it by unchecking the Custom Keystore setting in Project Settings -> Player -> Publishing Settings.

Not sure if that's a good move or not /shrug

**Comment by AlexThiv** [comment]
Thanks @SommerChase for bringing this up.

I changed the settings so that it won't try to use a custom Keystore as you did. You can see the commit [here](https://github.com/oculus-samples/Unity-SharedSpaces/commit/f0beb58f754b6b83d222b3afdcd8a84fdaa081d3)
