### ISSUE TITLE
Unable to open share link in the Invite Panel

### ISSUE THREAD

**Issue by nancywan1004** [oculus-samples/Unity-SharedSpaces#26]
Hi there,

I'm having trouble accessing the share link in the Invite Panel by pressing the share link button and it just shows me a popup saying there's trouble loading my share link. Any thoughts on what is missing here?

Update: I figured that the link would appear fine if I switch to my primary account on device which is also linked to my personal facebook account, but won't work if I use the other account added to the device and it was initially created through my work email.

Thanks!

**Comment by AlexThiv** [comment]
Hi @nancywan1004,
Sorry for the delay in response, we haven't been able to reproduce the issue you have noticed. Do you have some logs we might be able to look at? `adb logcat` would help us see if there is any issues on the device when processing the join link.

Can you make sure that both users are on the same channel for the application in the developer web portal?
