### ISSUE TITLE
DllNotFoundException when running Startup scene in Unity Editor

### ISSUE THREAD

**Issue by chiarainn** [oculus-samples/Unity-SharedSpaces#27]
Good morning, I configured the project as in the authors' notes, and was able to install the application on my Quest Pro. 
However, upon opening the application I find myself in a completely empty white room; no panel is present nor is my avatar. 
I then tried to run the Startup scene in Unity Editor, and this error pops up in the Unity Console: 
DllNotFoundException: LibOVRPlatform64_1 assembly:<unknown assembly> type:<unknown type> member:(null)
Oculus.Platform.WindowsPlatform.AsyncInitialize(System.String appId) (at Library/PackageCache/com.meta.xr.sdk.platform@59.0.0/Scripts/WindowsPlatform.cs:43)
Oculus.Platform.Core.AsyncInitialize (System.String appId) (at Library/PackageCache/com.meta.xr.sdk.platform@59.0.0/Scripts/Platform.cs:74)
SharedSpacesApplication+<Init>d__21.MoveNext () (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:172)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <53aac14d88ba4477acc998b039cfd73a>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
SharedSpacesApplication:Start() (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:167)

Are these two things connected? how do I manage to resolve this issue? 
Thanks

**Comment by jasonmeisel** [comment]
Thank you for reporting these issues! For the first issue, could you give some additional information:
- Unity version
- Unity logs from the device (`adb logcat -s Unity`)
- Did you set up [Photon](https://github.com/oculus-samples/Unity-SharedSpaces?tab=readme-ov-file#setting-up-photon) and [Oculus Platform](https://github.com/oculus-samples/Unity-SharedSpaces?tab=readme-ov-file#c-oculus-application-configuration) before building?

For the Editor issue, do you have the Oculus PC app installed? It's required to use Link. More information here: https://www.meta.com/help/quest/articles/headsets-and-accessories/oculus-link/set-up-link/
