### ISSUE TITLE
Unable to get this app anymore from applab with quest 3 or quest 2

### ISSUE THREAD

**Issue by juansuerorobotics** [oculus-samples/Unity-SharedSpaces#28]
I have two meta accounts, one for my quest 3 and one for my quest 2.

i am unable to get the unity version of shared spaces from any of those app labs.

the only one i can see is the shared spaces for UNREAL and only on my quest 2.

ive done everything that was told.  i logged into different browsers on my laptop, with the meta quest account that is associated with each headset and went to the link for the unity shares spaces and pressed "get" or "purchased"

but the apps never appeared on my headset or in the oculus app for me to install on the headset.  other applab things ive used appear on both.

i guess i have to do a manual install??

**Comment by juansuerorobotics** [comment]
takes a little while to hit the store search results

**Comment by AlexThiv** [comment]
Were you able to get it?

Did you try restarting the headset? I can take a bit of time before the headset knows that the app was purchased

**Comment by juansuerorobotics** [comment]
yes eventually i was able to get two meta quest 3s to use the unity
version.   i didnt go back to verify the meta quest 2
