### ISSUE TITLE
How do change this to use unity gaming services for the basic multiplayer part?   and also host my own server?

### ISSUE THREAD

**Issue by juansuerorobotics** [oculus-samples/Unity-SharedSpaces#29]
How do change this to use unity gaming services for the basic multiplayer part?   and also host my own server?

**Comment by AlexThiv** [comment]
To do that, you would have to replace the Photon Realtime implementation with Unity gaming services implementation. The whole project is already implemented using Netcode for gameobject so the part that needs to be updated is the transport layer.

The bulk of the changes would be in [NetworkLayer](https://github.com/oculus-samples/Unity-SharedSpaces/blob/main/Assets/SharedSpaces/Scripts/SharedSpacesNetworkLayer.cs).

You would also have to consider a different solution for Voice chat.
