### ISSUE TITLE
Entitlement check fails when running sample in unity editor

### ISSUE THREAD

**Issue by ryandle** [oculus-samples/Unity-SharedSpaces#3]
Is it supported to run this example within the unity player? I've followed the steps in the readme, but when I try to run it, I hit entitlement check failures for the app id I registered & configured in OculusPlatformSettings.asset.

(I've also tried to build & run the app on the quest directly, it doesn't get to the lobby and I'm not sure how to collect logs in that case - still learning unity.)

Here's the logs when it is run in the unity player:

> Unity v2020.3.25f1, Oculus Utilities v1.67.0, OVRPlugin v1.67.0, SDK v1.0.20.
> UnityEngine.Debug:Log (object)
> OVRManager:InitOVRManager () (at Packages/Oculus/VR/Scripts/OVRManager.cs:1436)
> OVRManager:Awake () (at Packages/Oculus/VR/Scripts/OVRManager.cs:1594)
> 
> SystemHeadset Oculus_Link_Quest_2, API OpenXR
> UnityEngine.Debug:LogFormat (string,object[])
> OVRManager:InitOVRManager () (at Packages/Oculus/VR/Scripts/OVRManager.cs:1441)
> OVRManager:Awake () (at Packages/Oculus/VR/Scripts/OVRManager.cs:1594)
> 
> OpenXR instance 0x54D800000001 session 0x0
> UnityEngine.Debug:LogFormat (string,object[])
> OVRManager:InitOVRManager () (at Packages/Oculus/VR/Scripts/OVRManager.cs:1445)
> OVRManager:Awake () (at Packages/Oculus/VR/Scripts/OVRManager.cs:1594)
> 
> Current display frequency 0, available frequencies []
> UnityEngine.Debug:LogFormat (string,object[])
> OVRManager:InitOVRManager () (at Packages/Oculus/VR/Scripts/OVRManager.cs:1543)
> OVRManager:Awake () (at Packages/Oculus/VR/Scripts/OVRManager.cs:1594)
> 
> TcpListener started. Local endpoint: 0.0.0.0:32419
> UnityEngine.Debug:LogFormat (string,object[])
> OVRNetwork/OVRNetworkTcpServer:StartListening (int) (at Packages/Oculus/VR/Scripts/Util/OVRNetwork.cs:95)
> OVRSystemPerfMetrics/OVRSystemPerfMetricsTcpServer:OnEnable () (at Packages/Oculus/VR/Scripts/Util/OVRSystemPerfMetrics.cs:186)
> UnityEngine.GameObject:AddComponent<OVRSystemPerfMetrics/OVRSystemPerfMetricsTcpServer> ()
> OVRManager:InitOVRManager () (at Packages/Oculus/VR/Scripts/OVRManager.cs:1554)
> OVRManager:Awake () (at Packages/Oculus/VR/Scripts/OVRManager.cs:1594)
> 
> [OVRNetworkTcpServer] Start Listening on port 32419
> UnityEngine.Debug:LogFormat (string,object[])
> OVRNetwork/OVRNetworkTcpServer:StartListening (int) (at Packages/Oculus/VR/Scripts/Util/OVRNetwork.cs:107)
> OVRSystemPerfMetrics/OVRSystemPerfMetricsTcpServer:OnEnable () (at Packages/Oculus/VR/Scripts/Util/OVRSystemPerfMetrics.cs:186)
> UnityEngine.GameObject:AddComponent<OVRSystemPerfMetrics/OVRSystemPerfMetricsTcpServer> ()
> OVRManager:InitOVRManager () (at Packages/Oculus/VR/Scripts/OVRManager.cs:1554)
> OVRManager:Awake () (at Packages/Oculus/VR/Scripts/OVRManager.cs:1594)
> 
> [OVRManager] OnApplicationPause(false)
> UnityEngine.Debug:Log (object)
> OVRManager:OnApplicationPause (bool) (at Packages/Oculus/VR/Scripts/OVRManager.cs:2178)
> 
> [OVRManager] OnApplicationFocus(true)
> UnityEngine.Debug:Log (object)
> OVRManager:OnApplicationFocus (bool) (at Packages/Oculus/VR/Scripts/OVRManager.cs:2186)
> 
> Group Presence set successfully
> UnityEngine.Debug:Log (object)
> SharedSpacesGroupPresenceState/<Set>d__17:MoveNext () (at Assets/SharedSpaces/Scripts/SharedSpacesGroupPresenceState.cs:65)
> UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
> SharedSpacesApplication/<Init>d__20:MoveNext () (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:183)
> UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
> SharedSpacesApplication:Start () (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:164)
> 
> ------GROUP PRESENCE STATE------
> UnityEngine.Debug:Log (object)
> SharedSpacesGroupPresenceState:Print () (at Assets/SharedSpaces/Scripts/SharedSpacesGroupPresenceState.cs:73)
> SharedSpacesGroupPresenceState/<Set>d__17:MoveNext () (at Assets/SharedSpaces/Scripts/SharedSpacesGroupPresenceState.cs:66)
> UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
> SharedSpacesApplication/<Init>d__20:MoveNext () (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:183)
> UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
> SharedSpacesApplication:Start () (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:164)
> 
> Destination:      Lobby
> UnityEngine.Debug:Log (object)
> SharedSpacesGroupPresenceState:Print () (at Assets/SharedSpaces/Scripts/SharedSpacesGroupPresenceState.cs:74)
> SharedSpacesGroupPresenceState/<Set>d__17:MoveNext () (at Assets/SharedSpaces/Scripts/SharedSpacesGroupPresenceState.cs:66)
> UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
> SharedSpacesApplication/<Init>d__20:MoveNext () (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:183)
> UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
> SharedSpacesApplication:Start () (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:164)
> 
> Lobby Session ID: Lobby-2739e040
> UnityEngine.Debug:Log (object)
> SharedSpacesGroupPresenceState:Print () (at Assets/SharedSpaces/Scripts/SharedSpacesGroupPresenceState.cs:75)
> SharedSpacesGroupPresenceState/<Set>d__17:MoveNext () (at Assets/SharedSpaces/Scripts/SharedSpacesGroupPresenceState.cs:66)
> UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
> SharedSpacesApplication/<Init>d__20:MoveNext () (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:183)
> UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
> SharedSpacesApplication:Start () (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:164)
> 
> Match Session ID: 
> UnityEngine.Debug:Log (object)
> SharedSpacesGroupPresenceState:Print () (at Assets/SharedSpaces/Scripts/SharedSpacesGroupPresenceState.cs:76)
> SharedSpacesGroupPresenceState/<Set>d__17:MoveNext () (at Assets/SharedSpaces/Scripts/SharedSpacesGroupPresenceState.cs:66)
> UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
> SharedSpacesApplication/<Init>d__20:MoveNext () (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:183)
> UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
> SharedSpacesApplication:Start () (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:164)
> 
> Joinable?:        True
> UnityEngine.Debug:Log (object)
> SharedSpacesGroupPresenceState:Print () (at Assets/SharedSpaces/Scripts/SharedSpacesGroupPresenceState.cs:77)
> SharedSpacesGroupPresenceState/<Set>d__17:MoveNext () (at Assets/SharedSpaces/Scripts/SharedSpacesGroupPresenceState.cs:66)
> UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
> SharedSpacesApplication/<Init>d__20:MoveNext () (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:183)
> UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
> SharedSpacesApplication:Start () (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:164)
> 
> --------------------------------
> UnityEngine.Debug:Log (object)
> SharedSpacesGroupPresenceState:Print () (at Assets/SharedSpaces/Scripts/SharedSpacesGroupPresenceState.cs:78)
> SharedSpacesGroupPresenceState/<Set>d__17:MoveNext () (at Assets/SharedSpaces/Scripts/SharedSpacesGroupPresenceState.cs:66)
> UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
> SharedSpacesApplication/<Init>d__20:MoveNext () (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:183)
> UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
> SharedSpacesApplication:Start () (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:164)
> 
> OVRControllerHelp: Active controller type: QuestAndRiftS for product Oculus Quest
> UnityEngine.Debug:LogFormat (string,object[])
> OVRControllerHelper:Start () (at Packages/Oculus/VR/Scripts/Util/OVRControllerHelper.cs:93)
> 
> OVRControllerHelp: Active controller type: QuestAndRiftS for product Oculus Quest
> UnityEngine.Debug:LogFormat (string,object[])
> OVRControllerHelper:Start () (at Packages/Oculus/VR/Scripts/Util/OVRControllerHelper.cs:93)
> 
> [OVRManager] HMDAcquired event
> UnityEngine.Debug:Log (object)
> OVRManager:Update () (at Packages/Oculus/VR/Scripts/OVRManager.cs:1786)
> 
> [OVRManager] InputFocusLost event
> UnityEngine.Debug:Log (object)
> OVRManager:Update () (at Packages/Oculus/VR/Scripts/OVRManager.cs:1874)
> 
> Recenter event detected
> UnityEngine.Debug:Log (object)
> OVRDisplay:Update () (at Packages/Oculus/VR/Scripts/OVRDisplay.cs:122)
> OVRManager:Update () (at Packages/Oculus/VR/Scripts/OVRManager.cs:1978)
> 
> Oculus Platform SDK initialized successfully
> UnityEngine.Debug:Log (object)
> SharedSpacesApplication:OnOculusPlatformInitialized (Oculus.Platform.Message`1<Oculus.Platform.Models.PlatformInitialize>) (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:208)
> Oculus.Platform.Request`1<Oculus.Platform.Models.PlatformInitialize>:HandleMessage (Oculus.Platform.Message) (at Packages/Oculus/Platform/Scripts/Request.cs:68)
> Oculus.Platform.Callback:HandleMessage (Oculus.Platform.Message) (at Packages/Oculus/Platform/Scripts/Callback.cs:162)
> Oculus.Platform.Callback:RunCallbacks () (at Packages/Oculus/Platform/Scripts/Callback.cs:61)
> Oculus.Platform.Request:RunCallbacks (uint) (at Packages/Oculus/Platform/Scripts/Request.cs:130)
> Oculus.Platform.CallbackRunner:Update () (at Packages/Oculus/Platform/Scripts/CallbackRunner.cs:28)
> 
> You are not entitled to use this app
> UnityEngine.Debug:LogError (object)
> SharedSpacesApplication:LogError (string,Oculus.Platform.Models.Error) (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:299)
> SharedSpacesApplication:<OnOculusPlatformInitialized>b__21_0 (Oculus.Platform.Message) (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:214)
> Oculus.Platform.Request:HandleMessage (Oculus.Platform.Message) (at Packages/Oculus/Platform/Scripts/Request.cs:113)
> Oculus.Platform.Callback:HandleMessage (Oculus.Platform.Message) (at Packages/Oculus/Platform/Scripts/Callback.cs:162)
> Oculus.Platform.Callback:RunCallbacks () (at Packages/Oculus/Platform/Scripts/Callback.cs:61)
> Oculus.Platform.Request:RunCallbacks (uint) (at Packages/Oculus/Platform/Scripts/Request.cs:130)
> Oculus.Platform.CallbackRunner:Update () (at Packages/Oculus/Platform/Scripts/CallbackRunner.cs:28)
> 
> ERROR MESSAGE:   Missing entitlement for 4986813654673010 (1971031)
> UnityEngine.Debug:LogError (object)
> SharedSpacesApplication:LogError (string,Oculus.Platform.Models.Error) (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:300)
> SharedSpacesApplication:<OnOculusPlatformInitialized>b__21_0 (Oculus.Platform.Message) (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:214)
> Oculus.Platform.Request:HandleMessage (Oculus.Platform.Message) (at Packages/Oculus/Platform/Scripts/Request.cs:113)
> Oculus.Platform.Callback:HandleMessage (Oculus.Platform.Message) (at Packages/Oculus/Platform/Scripts/Callback.cs:162)
> Oculus.Platform.Callback:RunCallbacks () (at Packages/Oculus/Platform/Scripts/Callback.cs:61)
> Oculus.Platform.Request:RunCallbacks (uint) (at Packages/Oculus/Platform/Scripts/Request.cs:130)
> Oculus.Platform.CallbackRunner:Update () (at Packages/Oculus/Platform/Scripts/CallbackRunner.cs:28)
> 
>

**Comment by ilyavitek** [comment]
As far as I understand it's not suppose to work in Editor.
Would be happy to be wrong about that and be able to run it in Editor, so far I was building it to check/test/try to make it work :)

**Comment by jasonmeisel** [comment]
> As far as I understand it's not suppose to work in Editor.

That is correct, as some Oculus platform features are only available on Quest.

However, this particular error (Missing entitlement) is likely due to using a Quest App Id as your Rift App Id. You must create a Rift app in the developer dashboard to get an App Id for testing on PC.

You can also group the Rift and Quest apps to share some of their settings by following [this guide](https://developer.oculus.com/documentation/native/ps-cross-device-app-groupings/).
