### ISSUE TITLE
UnitySharedSpaces from github doesnt show avatar while the UnitySharedspaces already in applab works fine

### ISSUE THREAD

**Issue by juansuerorobotics** [oculus-samples/Unity-SharedSpaces#31]
Hello,

I got UnitySharedspaces to work across two meta quest 3 devices by using the already deployed app from applab.
Then i download the github code and followed the video and blog instructions for deployment.
when i run those from github both headsets do not show the avatar and im not able to move around the room im stuck in the middle of the room.   When i lift my hands up the controllers are there and even animate when i press the joystick.

**Comment by juansuerorobotics** [comment]
i fixed the appids in my setup.  to correspond to the proper appids
that got it to work.   you have to make a corresponding service in photon cloud for each of those services like voice, chat, fusion, realtime etc.

**Comment by jasonmeisel** [comment]
That's correct. Glad you were able to get it working!
