### ISSUE TITLE
I did all the step and open the game and just a blank space. How to fix it? Thank you

### ISSUE THREAD

**Issue by tutaharmonyat** [oculus-samples/Unity-SharedSpaces#32]
<img width="548" alt="123" src="https://github.com/oculus-samples/Unity-SharedSpaces/assets/92135588/820f8c70-ef96-45aa-9e72-7c6c17d9ebc5">

I open the game and just see a blank space.

**Comment by hezzze** [comment]
same here, tried everything mentioned #22 here as well, still not working on the Quest 3 device
