### ISSUE TITLE
Starting the app Throws NullReferenceException at SharedSpacesApplication.OnClientConnected

### ISSUE THREAD

**Issue by ilyavitek** [oculus-samples/Unity-SharedSpaces#4]
Trying to make that sample work on my machine with my test app.

One of the first issues were Entitlements, since there are nothing about them in Readme I assumed that it should work, but I was stuck in empty scene. Fixed that by adding entitlements to my test App in Oculus Dashboard (maybe it would make sense to mention that in Readme).

Next issue was not seeing Avatar, for some reason I had nothing assigned to PlayerPrefab in SharedSpacesNetworkLayer GO (Startup Scene). Fixed by referencing SharedSpacesPlayer.prefab.

At the moment game starts and I can run around with my avatar, but there are two issues:

1. As soon as I start I am seeing NullReferenceException at SharedSpacesApplication.OnClientConnected (looks like session = FindObjectOfType<SharedSpacesSession>(); sets session to null and then session.RequestSpawnServerRpc throws that, not sure why SharedSpacesSession is not spawned).

![Screenshot 2022-01-31 at 17 30 46](https://user-images.githubusercontent.com/10454693/151985264-0c164833-b15e-4857-91fc-4280e61caf35.png)

2. I think that this issue may be solved after the first one is solved, but as soon as I join any room I appear in the room, but without avatar and from then on I can not do much.

<img width="1201" alt="Screenshot 2022-01-31 at 15 32 56" src="https://user-images.githubusercontent.com/10454693/151985477-81534abc-624a-4980-a131-5533687349e5.png">

Would appreciate any help :)

You can find one of the latest states of my fork here: https://github.com/ilyavitek/Unity-SharedSpaces

**Comment by ilyavitek** [comment]
I realised that it was unnecessary to reference SharedSpacesPlayer.prefab to PlayerPrefab field in SharedSpacesNetworkLayer GO (it was even causing an issue of two avatars for 1 user).

**Comment by ilyavitek** [comment]
At the moment it seems to me that somehow in my setup I am getting OnHostStarted after OnClientConnected for the first player and that causes NullRef for session (since it's spawned in OnHostStarted, but we're using it in  OnClientConnected).
I've applied a hot fix (https://github.com/ilyavitek/Unity-SharedSpaces/commit/771ec3ff78a6ccb781b28b5cb2fd438bd66f0c8c), but I am not sure if that's ok to leave it like that 😄 

After that hot fix it works a bit better, but still not 100% of functionality.

**Comment by ilyavitek** [comment]
It seems like the main issue is that this "race condition" for the Host (`OnClientConnected` is called earlier than `OnHostStarted`)  breaks the flow and with that fix above single player works, but multiplayer then has the same issue (Client gets NullRef in OnClientConnected too, basically FindObjectOfType<SharedSpacesSession>() returns null).

Is there any specific reason why that "race condition" or problem with SharedSpacesSession for both host and client may be happening?

**Comment by hensoup** [comment]
I'm having the same issue myself it keeps poping up this:

NullReferenceException: Object reference not set to an instance of an object
SharedSpacesApplication.OnClientConnected (System.UInt64 clientId) (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:88)
