### ISSUE TITLE
Why is realtime being used instead of fusion?

### ISSUE THREAD

**Issue by MonoFlauta** [oculus-samples/Unity-SharedSpaces#5]
Hello!
I wanted to ask you why you have decided to use [Realtime](https://www.photonengine.com/en-US/Realtime) instead of [Fusion](https://www.photonengine.com/en-US/Fusion) photon service. We are currently trying to decide which technology to use for a project and we have found this project to be really useful but, at least for now, we thought that Fusion was probably a better solution than Realtime when working with Unity.
Could you provide us with more insight into that decision? We would greatly appreciate it!
Thank you very much and thank you for this great example :)

**Comment by jasonmeisel** [comment]
Hi @MonoFlauta!

We chose to use Realtime for a few reasons:
1. Photon Fusion is still in beta, and we wanted to demonstrate a simple and reliable way to add multiplayer.
2. Photon Realtime is available for Unreal, so the [Unreal version of SharedSpaces](https://github.com/oculus-samples/Unreal-SharedSpaces) is able to demonstrate the same functionality as the Unity version.
3. Photon Realtime is available as a transport for [Netcode for GameObjects](https://docs-multiplayer.unity3d.com/docs/getting-started/about/index.html), so by using it, SharedSpaces should be fairly easy to use with other transports. In fact, it should be possible to build a Fusion transport and use it in SharedSpaces.

With those in mind, Photon Realtime was the best fit for this sample. It may be the best fit for your project as well, but other networking solutions (like Photon Fusion) are worth considering as well.

Hope that helps!

**Comment by MonoFlauta** [comment]
It does, thank you very much!
