### ISSUE TITLE
Null Refrence when running.

### ISSUE THREAD

**Issue by hensoup** [oculus-samples/Unity-SharedSpaces#7]
NullReferenceException: Object reference not set to an instance of an object
SharedSpacesApplication.OnClientConnected (System.UInt64 clientId) (at Assets/SharedSpaces/Scripts/SharedSpacesApplication.cs:88)

**Comment by ilyavitek** [comment]
If you revert to initial commit it should work, looks like that problem comes after Netcode upgrade.
