### ISSUE TITLE
Amount of simultaneous players

### ISSUE THREAD

**Issue by ilyavitek** [oculus-samples/Unity-SharedSpaces#8]
Hi!

- Do you have an idea of how many players a room in this setup can hold at the same time without lagging issue?

- Was it tested on more than 3 players?

Seems like Photon region setting can affect that, but we were having issues with testing it when there were more than 3-4 players.

Any info regarding that topic can be useful.
Thanks!

**Comment by pr0-zac** [comment]
Photon region can definitely affect performance. If you're just testing out the project, the easiest way to fix this is:
* Go to your [Photon dashboard](https://dashboard.photonengine.com/)
* Click Manage below the associated app
* Scroll down to the bottom of the page to find the Regions Whitelist
* Add the region you are in (e.g. usw;) from the [available regions](https://doc.photonengine.com/en-us/realtime/current/connection-and-authentication/regions#available_regions)

If you will be using this for a published title, you'll want to add [runtime region selection logic.](https://doc.photonengine.com/en-us/realtime/current/connection-and-authentication/regions#how_to_select_a_region_at_runtime)

We ran a test with 6 players in Unity SharedSpaces just now and had no noticeable lag. Please let us know if changing regions fixes your issue.

**Comment by ilyavitek** [comment]
Thanks for your answer!

Yeah, we have changed the region and it was significantly better.

We'll be testing it for 6+ users later this week.

**Comment by pr0-zac** [comment]
Glad to hear it's working better for you! 

Gonna close this issue. Would be great if you could comment letting us know how your play test went.
